name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  NODE_VERSION: 22

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Auth CLI
        run: |
          npx wix login --api-key $WIX_AUTH_TOKEN
        env:
          WIX_AUTH_TOKEN: ${{ secrets.WIX_AUTH_TOKEN }}

      - name: Pull environment variables
        run: |
          npx wix env pull

      - name: Capture environment info
        run: |
          mkdir -p .wix
          echo "=== Environment Information ===" > .wix/debug.log
          echo "Node.js version: $(node --version)" >> .wix/debug.log
          echo "npm version: $(npm --version)" >> .wix/debug.log
          echo "Wix CLI version: $(npx wix --version)" >> .wix/debug.log
          echo "GitHub SHA: ${{ github.sha }}" >> .wix/debug.log
          echo "GitHub Ref: ${{ github.ref }}" >> .wix/debug.log
          echo "Build timestamp: $(date)" >> .wix/debug.log
          echo "================================" >> .wix/debug.log

      - name: Build project
        run: |
          echo "=== Build Output ===" >> .wix/debug.log
          npm run build 2>&1 | tee -a .wix/debug.log
          echo "=== Build Complete ===" >> .wix/debug.log

      - name: Deploy preview
        run: |
          set -o pipefail
          echo "=== Preview Deployment Output ===" >> .wix/debug.log
          npm run preview 2>&1 | tee -a .wix/debug.log
          echo "=== Preview Deployment Complete ===" >> .wix/debug.log
        env:
          WIX_AUTH_TOKEN: ${{ secrets.WIX_AUTH_TOKEN }}

      - name: Upload debug logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: wix-debug-logs-preview
          path: |
            .wix/debug.log
            .wix/*.log
          retention-days: 30

      - name: Upload build artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-preview
          path: |
            dist/
            .astro/
          retention-days: 30

      - name: Get preview URL from topology
        id: preview-url
        run: |
          if [ -f ".wix/topology.json" ]; then
            PREVIEW_URL=$(cat .wix/topology.json | jq -r '.preview.site.main')
            echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
            echo "Preview URL: $PREVIEW_URL"
          else
            echo "preview_url=" >> $GITHUB_OUTPUT
            echo "Preview URL: Not found in topology.json"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.preview-url.outputs.preview_url }}';
            const workflowStatus = '${{ job.status }}';

            let comment;
            if (workflowStatus === 'success' && previewUrl) {
              comment = `## 🚀 Preview Deployment

              Your changes have been deployed to a preview environment!
              
              **Preview URL:** ${previewUrl}
              
              ---
              *This preview will be automatically updated when you push new commits to this PR.*`;
            } else {
              comment = `## ❌ Preview Deployment Failed

              The preview deployment failed. Debug logs and build artifacts have been uploaded as workflow artifacts.
              
              **Debug Logs:** Available in the "wix-debug-logs-preview" artifact
              **Build Artifacts:** Available in the "build-artifacts-preview" artifact
              
              ---
              *Please check the workflow logs and artifacts for more details.*`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
      - uses: ./.github/actions/setup-playwright

      - uses: ./.github/actions/run-playwrite
        with:
          deployment-url: ${{ steps.preview-url.outputs.preview_url }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prNumber: ${{ github.event.pull_request.number }}

