name: Deploy Production

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "22"

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Auth CLI
        run: |
          npx wix login --api-key $WIX_AUTH_TOKEN
        env:
          WIX_AUTH_TOKEN: ${{ secrets.WIX_AUTH_TOKEN }}

      - name: Pull environment variables
        run: |
          npx wix env pull

      - name: Capture environment info
        run: |
          mkdir -p .wix
          echo "=== Environment Information ===" > .wix/debug.log
          echo "Node.js version: $(node --version)" >> .wix/debug.log
          echo "npm version: $(npm --version)" >> .wix/debug.log
          echo "Wix CLI version: $(npx wix --version)" >> .wix/debug.log
          echo "GitHub SHA: ${{ github.sha }}" >> .wix/debug.log
          echo "GitHub Ref: ${{ github.ref }}" >> .wix/debug.log
          echo "Build timestamp: $(date)" >> .wix/debug.log
          echo "================================" >> .wix/debug.log

      - name: Build project
        run: |
          echo "=== Build Output ===" >> .wix/debug.log
          npm run build 2>&1 | tee -a .wix/debug.log
          echo "=== Build Complete ===" >> .wix/debug.log

      - name: Deploy to production
        run: |
          echo "=== Deployment Output ===" >> .wix/debug.log
          npm run release 2>&1 | tee -a .wix/debug.log
          echo "=== Deployment Complete ===" >> .wix/debug.log
        env:
          WIX_AUTH_TOKEN: ${{ secrets.WIX_AUTH_TOKEN }}

      - name: Upload debug logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: wix-debug-logs
          path: |
            .wix/debug.log
            .wix/*.log
          retention-days: 30

      - name: Upload build artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            .astro/
          retention-days: 30

      - name: Notify deployment success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## ✅ Production Deployment Successful

            Your changes have been successfully deployed to production!

            **Production URL:** https://kitchensink-netanelg4.wix-host.com

            ---
            *Deployed at: ${new Date().toISOString()}*`;

            // Create a deployment status
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.sha,
              state: 'success',
              description: 'Production deployment completed successfully',
              environment_url: 'https://kitchensink-netanelg4.wix-host.com'
            });

      - name: Notify deployment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## ❌ Production Deployment Failed

            The production deployment failed. Debug logs and build artifacts have been uploaded as workflow artifacts.

            **Debug Logs:** Available in the "wix-debug-logs" artifact
            **Build Artifacts:** Available in the "build-artifacts" artifact

            ---
            *Failed at: ${new Date().toISOString()}*`;

            // Create a deployment status
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.sha,
              state: 'failure',
              description: 'Production deployment failed - check artifacts for debug logs'
            });
